// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjArqsi.Infrastructure;

#nullable disable

namespace ProjArqsi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjArqsi.Domain.VesselTypeAggregate.VesselType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("VesselTypes", (string)null);
                });

            modelBuilder.Entity("ProjArqsi.Domain.VesselTypeAggregate.VesselType", b =>
                {
                    b.OwnsOne("ProjArqsi.Domain.VesselTypeAggregate.MaxBays", "MaxBays", b1 =>
                        {
                            b1.Property<Guid>("VesselTypeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("MaxBays");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("ProjArqsi.Domain.VesselTypeAggregate.MaxRows", "MaxRows", b1 =>
                        {
                            b1.Property<Guid>("VesselTypeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("MaxRows");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("ProjArqsi.Domain.VesselTypeAggregate.MaxTiers", "MaxTiers", b1 =>
                        {
                            b1.Property<Guid>("VesselTypeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("MaxTiers");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("ProjArqsi.Domain.VesselTypeAggregate.TypeCapacity", "TypeCapacity", b1 =>
                        {
                            b1.Property<Guid>("VesselTypeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("TypeCapacity");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("ProjArqsi.Domain.VesselTypeAggregate.TypeDescription", "TypeDescription", b1 =>
                        {
                            b1.Property<Guid>("VesselTypeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TypeDescription");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("ProjArqsi.Domain.VesselTypeAggregate.TypeName", "TypeName", b1 =>
                        {
                            b1.Property<Guid>("VesselTypeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TypeName");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.Navigation("MaxBays")
                        .IsRequired();

                    b.Navigation("MaxRows")
                        .IsRequired();

                    b.Navigation("MaxTiers")
                        .IsRequired();

                    b.Navigation("TypeCapacity")
                        .IsRequired();

                    b.Navigation("TypeDescription")
                        .IsRequired();

                    b.Navigation("TypeName")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
