@startuml systemUser

left to right direction
skinparam packageStyle rectangle

actor "System User" as User

rectangle "Port Management System - SPA" {
  ' Sprint B - SPA & UI
  usecase "US 3.1.2\nUnified Layout" as UC312
  usecase "US 3.1.3\nRole-Based Menu\nVisibility" as UC313
  usecase "US 3.1.4\nUser Feedback\non Actions" as UC314
  usecase "US 3.1.5\nPages/Forms for\nUser Actions" as UC315
  
  ' Sprint B - Authentication & Authorization
  usecase "US 3.2.1\nExternal IAM\nAuthentication" as UC321
  usecase "US 3.2.2\nLoad Internal\nAuthorization Role" as UC322
  usecase "US 3.2.3\nMaintain Secure\nSession" as UC323
  usecase "US 3.2.4\nRole-Based Access\nControl" as UC324
  usecase "US 3.2.6\nUser Activation\nvia Link" as UC326
}

User --> UC312
User --> UC313
User --> UC314
User --> UC315
User --> UC321
User --> UC322
User --> UC323
User --> UC324
User --> UC326

@enduml
